# Generated by Django 6.1.1 on 2026-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
