# Generated by Django 6.1.1 on 2026-09-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_album_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='views',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
