# Generated by Django 6.1.1 on 2026-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geekmodel',
            name='landcreated',
            field=models.TimeField(auto_now=True),
        ),
    ]
