# Generated by Django 6.1.1 on 2026-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_geekmodel_landcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='geekmodel',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatars/'),
        ),
    ]
